/***********************************************************************
* copyright (c) 2004 MALET Jean-luc aka cityhunter
* This program is free software; you can redistribute it and/or modify
* it under the terms of the artistic license as published in the top source dir of the
* package
************************************************************************/



#define __ML_MODULES
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <OpenML/OpenML.h>

int32_t MLAPI
mlPvParamToString(u_int64_t objectId, MLpv* pv, char* str, int16_t* bufferSize)
{
	const struct mlparamtoname* current=params;
	int i=0;
	while (i < ML_PARAM_COUNT && pv->param != current->param )
		{
			current++;
			i++;
		}
	if ( i == ML_PARAM_COUNT)
		return EINVAL;
	*bufferSize-=snprintf (str, current->length,"%s",current->name);
	return errno;
}

const struct mlparamtoname params[] ={
	CONSTRUCT_NAME_ARRAY(ML_TYPE_NONE)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_BYTE)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT16)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT64)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_REAL32)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_REAL64)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_BYTE_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT16_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT32_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT64_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_REAL32_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_REAL64_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_PV_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_BYTE_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT16_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT32_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_INT64_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_REAL32_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_REAL64_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_PV_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_TYPE_MSG_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_ENGINE_TYPE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_IMPLEMENTATION_TYPE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_PIXEL_LINE_ALIGNMENT_INT32)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_EXTENSIONS_BYTE_ARRAY)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_SRC_PIPE_IDS)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_DEST_PIPE_IDS)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_SRC_COUNT)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_DEST_COUNT)
	CONSTRUCT_NAME_ARRAY(ML_PIPE_TYPE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_SPATIAL_QUALITY_REAL32)
	CONSTRUCT_NAME_ARRAY(ML_XCODE_BITRATE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_ID)
	CONSTRUCT_NAME_ARRAY(ML_NAME)
	CONSTRUCT_NAME_ARRAY(ML_SYSTEM_DEVICE_IDS)
	CONSTRUCT_NAME_ARRAY(ML_PARENT_ID)
	CONSTRUCT_NAME_ARRAY(ML_FEATURES)
	CONSTRUCT_NAME_ARRAY(ML_DEVICE_VERSION)
	CONSTRUCT_NAME_ARRAY(ML_DEVICE_INDEX)
	CONSTRUCT_NAME_ARRAY(ML_DEVICE_LOCATION)
	CONSTRUCT_NAME_ARRAY(ML_DEVICE_JACK_IDS)
	CONSTRUCT_NAME_ARRAY(ML_DEVICE_PATH_IDS)
	CONSTRUCT_NAME_ARRAY(ML_DEVICE_XCODE_IDS)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_IDS)
	CONSTRUCT_NAME_ARRAY(ML_OPEN_OPTIONS_IDS)
	CONSTRUCT_NAME_ARRAY(ML_PRESET)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_TYPE)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_ACCESS)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_DEFAULT)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_MINS)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_MAXS)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_INCREMENT)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_ENUM_VALUES)
	CONSTRUCT_NAME_ARRAY(ML_PARAM_ENUM_NAMES)
	CONSTRUCT_NAME_ARRAY(ML_EVENT_QUEUE)
	CONSTRUCT_NAME_ARRAY(ML_EVENT_DEVICE)
	CONSTRUCT_NAME_ARRAY(ML_EVENT_VIDEO)
	CONSTRUCT_NAME_ARRAY(ML_EVENT_XCODE)
	CONSTRUCT_NAME_ARRAY(ML_EVENT_AUDIO)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_BUFFER_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_WIDTH_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_HEIGHT_1_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_HEIGHT_2_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_ROW_BYTES_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_SKIP_PIXELS_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_SKIP_ROWS_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_ORIENTATION_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_BUFFER_SIZE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_TEMPORAL_SAMPLING_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_INTERLEAVE_MODE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_DOMINANCE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_COMPRESSION_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_SAMPLING_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_COLORSPACE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_PACKING_INT32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_GAMMA_REAL32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_COMPRESSION_FACTOR_REAL32)
	CONSTRUCT_NAME_ARRAY(ML_IMAGE_ALPHA_FILL_INT32)
	CONSTRUCT_NAME_ARRAY(ML_HANC_WIDTH_INT32)
	CONSTRUCT_NAME_ARRAY(ML_HANC_HEIGHT_1_INT32)
	CONSTRUCT_NAME_ARRAY(ML_HANC_HEIGHT_2_INT32)
	CONSTRUCT_NAME_ARRAY(ML_HANC_FORMAT_INT32)
	CONSTRUCT_NAME_ARRAY(ML_HANC_BUFFER_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_VANC_WIDTH_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VANC_HEIGHT_1_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VANC_HEIGHT_2_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VANC_FORMAT_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VANC_BUFFER_POINTER)
	CONSTRUCT_NAME_ARRAY(ML_JACK_TYPE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_JACK_DIRECTION_INT32)
	CONSTRUCT_NAME_ARRAY(ML_JACK_COMPONENT_SIZE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_JACK_ALIAS_IDS)
	CONSTRUCT_NAME_ARRAY(ML_JACK_PATH_IDS)
	CONSTRUCT_NAME_ARRAY(ML_JACK_INTERNAL_ID)
	CONSTRUCT_NAME_ARRAY(ML_PATH_TYPE_INT32)
	CONSTRUCT_NAME_ARRAY(ML_PATH_SRC_JACK_ID)
	CONSTRUCT_NAME_ARRAY(ML_PATH_DST_JACK_ID)
	CONSTRUCT_NAME_ARRAY(MLI_PATH_INTERNAL_ID)
	CONSTRUCT_NAME_ARRAY(ML_PATH_PIXEL_LINE_ALIGNMENT_INT32 )
	CONSTRUCT_NAME_ARRAY(ML_PATH_BUFFER_ALIGNMENT_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_TIMING_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_PRECISION_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_SIGNAL_PRESENT_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_GENLOCK_SOURCE_ID)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_START_X_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_START_Y_F1_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_START_Y_F2_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_OUTPUT_REPEAT_INT32)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_UST_INT64)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_MSC_INT64)
	CONSTRUCT_NAME_ARRAY(ML_VIDEO_ASC_INT64)
	CONSTRUCT_NAME_ARRAY(ML_AUDIO_UST_INT64)
	CONSTRUCT_NAME_ARRAY(ML_AUDIO_MSC_INT64)
	CONSTRUCT_NAME_ARRAY(ML_AUDIO_ASC_INT64)
	CONSTRUCT_NAME_ARRAY(ML_IF_VIDEO_UST_LT)
	CONSTRUCT_NAME_ARRAY(ML_IF_AUDIO_UST_LT)
	CONSTRUCT_NAME_ARRAY(ML_WAIT_FOR_VIDEO_UST_INT64)
	CONSTRUCT_NAME_ARRAY(ML_WAIT_FOR_AUDIO_UST_INT64)
	CONSTRUCT_NAME_ARRAY(ML_WAIT_FOR_VIDEO_MSC_INT64)
	CONSTRUCT_NAME_ARRAY(ML_WAIT_FOR_AUDIO_MSC_INT64)
	};
